development:
  stripe_secret_key: sk_test_unAWZFCHzDaxLFkB0mhDOjGA
  stripe_publishable_key: pk_test_vah00gUofOknetuaB2dxk3CN
  mandrill_username: kaizenstorm@gmx.com
  mandrill_password: FRqrTQZMdOdKQK27xfzqCA

# production:
#   stripe_secret_key: sk_live_wc3Wd95g5jxIAlyXI07nHg7w
#   stripe_publishable_key: pk_live_cZ7F2UnWurr1MuSsRpukPiQp
#   mandrill_username:
#   mandrill_password: