default: &default
      adapter: postgresql
      encoding: SQL_ASCII
      pool: 5
      username: <%= ENV['USERNAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: mowerman_development

test: &TEST
  <<: *default
  database: mowerman_test
