development:
  adapter: postgresql
  database: kaizen_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: kaizen_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kaizen_production
  pool: 5
  timeout: 5000

