development:
  adapter: postgresql
  encoding: utf8
  database: mowerman_development
  pool: 5
  username: astorrer
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: mowerman_test
  pool: 5
  username: astorrer
  password:
