default: &default
      adapter: postgresql
      encoding: SQL_ASCII
      pool: 5
      username: <%= ENV['USERNAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: mowerman_development.sqlite3

test: &TEST
  <<: *default
  database: mowerman_test