require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlantasksController do

  # This should return the minimal set of attributes required to create a valid
  # Plantask. As you add validations to Plantask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "area" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlantasksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all plantasks as @plantasks" do
      plantask = Plantask.create! valid_attributes
      get :index, {}, valid_session
      assigns(:plantasks).should eq([plantask])
    end
  end

  describe "GET show" do
    it "assigns the requested plantask as @plantask" do
      plantask = Plantask.create! valid_attributes
      get :show, {:id => plantask.to_param}, valid_session
      assigns(:plantask).should eq(plantask)
    end
  end

  describe "GET new" do
    it "assigns a new plantask as @plantask" do
      get :new, {}, valid_session
      assigns(:plantask).should be_a_new(Plantask)
    end
  end

  describe "GET edit" do
    it "assigns the requested plantask as @plantask" do
      plantask = Plantask.create! valid_attributes
      get :edit, {:id => plantask.to_param}, valid_session
      assigns(:plantask).should eq(plantask)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Plantask" do
        expect {
          post :create, {:plantask => valid_attributes}, valid_session
        }.to change(Plantask, :count).by(1)
      end

      it "assigns a newly created plantask as @plantask" do
        post :create, {:plantask => valid_attributes}, valid_session
        assigns(:plantask).should be_a(Plantask)
        assigns(:plantask).should be_persisted
      end

      it "redirects to the created plantask" do
        post :create, {:plantask => valid_attributes}, valid_session
        response.should redirect_to(Plantask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plantask as @plantask" do
        # Trigger the behavior that occurs when invalid params are submitted
        Plantask.any_instance.stub(:save).and_return(false)
        post :create, {:plantask => { "area" => "invalid value" }}, valid_session
        assigns(:plantask).should be_a_new(Plantask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Plantask.any_instance.stub(:save).and_return(false)
        post :create, {:plantask => { "area" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested plantask" do
        plantask = Plantask.create! valid_attributes
        # Assuming there are no other plantasks in the database, this
        # specifies that the Plantask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Plantask.any_instance.should_receive(:update).with({ "area" => "MyString" })
        put :update, {:id => plantask.to_param, :plantask => { "area" => "MyString" }}, valid_session
      end

      it "assigns the requested plantask as @plantask" do
        plantask = Plantask.create! valid_attributes
        put :update, {:id => plantask.to_param, :plantask => valid_attributes}, valid_session
        assigns(:plantask).should eq(plantask)
      end

      it "redirects to the plantask" do
        plantask = Plantask.create! valid_attributes
        put :update, {:id => plantask.to_param, :plantask => valid_attributes}, valid_session
        response.should redirect_to(plantask)
      end
    end

    describe "with invalid params" do
      it "assigns the plantask as @plantask" do
        plantask = Plantask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Plantask.any_instance.stub(:save).and_return(false)
        put :update, {:id => plantask.to_param, :plantask => { "area" => "invalid value" }}, valid_session
        assigns(:plantask).should eq(plantask)
      end

      it "re-renders the 'edit' template" do
        plantask = Plantask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Plantask.any_instance.stub(:save).and_return(false)
        put :update, {:id => plantask.to_param, :plantask => { "area" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plantask" do
      plantask = Plantask.create! valid_attributes
      expect {
        delete :destroy, {:id => plantask.to_param}, valid_session
      }.to change(Plantask, :count).by(-1)
    end

    it "redirects to the plantasks list" do
      plantask = Plantask.create! valid_attributes
      delete :destroy, {:id => plantask.to_param}, valid_session
      response.should redirect_to(plantasks_url)
    end
  end

end
